mqttmsg 패키지 추가
jongkwang/IoTLabs pull request #39
Opened 2016-09-26 12:09 UTC by january89

MqttMsgDao 추가( 예제파일 참조하여 그대로 적용 )
MqttMsgMapper 추가( 쿼리 미완성 )

Configuration 수정( MqttMsgMapper 의존성 추가 )

2016-09-26 12:26 UTC, jongkwang commented
@toori67 님,
이쪽은 제가 보는 것 보다 직접 보시는 것이 좋겠습니다.

살펴보시고 Merge 부탁드려요 ^^;;

2016-09-26 12:29 UTC, toori67 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/Configuration.xml
> +        <mapper resource="org/iotlabs/db/mybatis/mqttmsg/MqttMsgMapper.xml" />
`main/resources/` 폴더 아래에 `sql` 이나 다른 이름으로 파일을 옮겨주실 수 있으신가요? 
e.g. `main/resources/sql/MainMapper.xml`, `main/resources/sql/mqttmsg/MqttMsgMapper.xml`

2016-09-26 12:34 UTC, toori67 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgDao.java
> +  private SqlSession session = MyBatisManager.getSqlMapper().openSession();
`session` 을 열었으면 꼭 `close` 를 호출해야 합니다!
(http://barunmo.blogspot.kr/2013/06/mybatis.html#MyBatis의 변화)

2016-09-26 12:35 UTC, toori67 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgDao.java
> +  private HashMap<String,MqttMsg> mqttMsgSelectOne(String query,MqttMsg msg){
access modifier 가 private 이네요. 👍  이긴 한데 밖에서 접근을 하지 않는 메소드인가요??

2016-09-26 12:37 UTC, toori67 requested changes
몇가지 사항만 수정하시면 좋을거 같습니다 :) 
- 전체적으로 xml 파일들을 resources/ 밑으로 옮겨주세요 :)
- open 된 세션을 close 꼭 해주세요!
- access modifier 를 확인해주세요!

2016-09-26 13:12 UTC, january89 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/Configuration.xml
> +        <mapper resource="org/iotlabs/db/mybatis/mqttmsg/MqttMsgMapper.xml" />
네 수정하였습니다~!

2016-09-26 13:13 UTC, january89 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgDao.java
> +  private SqlSession session = MyBatisManager.getSqlMapper().openSession();
이것도 수정하였습니다 ^^

2016-09-26 13:25 UTC, january89 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgDao.java
> +  private HashMap<String,MqttMsg> mqttMsgSelectOne(String query,MqttMsg msg){
퍼블릭으로 접근권한 변경 하였습니다! ^^

2016-09-26 15:56 UTC, toori67 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgDao.java
> +    return wrapSession(session.insert(query,map));
`session.insert` 에서 예외가 발생하면 session 이 안 닫힐거 같습니다 😭

2016-09-26 15:59 UTC, toori67 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgService.java
> +public interface MqttMsgService{
이 인터페이스의 의도를 잘 이해 못하겠습니다 ㅠㅠ 
CRUD 를 인터페이스로 정의하는 것이 의도라면 제네릭을 써서 유연하게 만드는게 어떨까요?
```java
interface DaoService<T> {
    Map<String, T> select(String q, T t);
    List<T> selectList(String q, T);
 ...
}
```

2016-09-26 16:00 UTC, toori67 requested changes
수정 pr 감사드립니다 🙇 👍 
아래 리뷰 사항을 조금만 더 수정하시면 매우 좋은 pull request 가 될거 같습니다! 😃

2016-09-26 16:00 UTC, toori67 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/Configuration.xml
> +        <mapper resource="/resources/sql/mqttmsg/MqttMsgMapper.xml" />
:+1:

2016-09-27 00:18 UTC, january89 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgService.java
> +public interface MqttMsgService{
너무 생각없이 의도없는 코드를 짠거 같아요! T_T 인터페이스는 삭제 했어요 ^^

2016-09-27 00:18 UTC, january89 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgDao.java
> +    return wrapSession(session.insert(query,map));
네! 수정했습니다!

2016-09-27 06:34 UTC, toori67 requested changes
💯

2016-09-27 06:34 UTC, toori67 commented on Platforms/Java/src/main/java/org/iotlabs/db/mybatis/mqttmsg/MqttMsgDao.java
> +    }finally {
💯

2016-09-27 06:35 UTC, merged